version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ${STREAM_STORAGE}:/opt/app/storage
    environment:
      - JAR_FILE=./build/libs/tvchannel-0.0.1-SNAPSHOT.jar
